[project]
name = "document-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.0",
    "docling>=2.59.0",
    "ipywidgets>=8.1.7",
    "pandas>=2.3.3",
]
